<?php

use \printconnect\Newsletters\Subscriptions\Factory;
use \printconnect\Customers;

function pcnewsletters_menu() {
  $items['newsletter'] = array(
      'title' => 'Newsletter',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('pcnewsletters_subscribe_form'),
      'access arguments' => array('access content'),
          //'file' => 'pcnewsletters.forms.inc',
  );
  $items['newsletter/subscribe'] = array(
      'title' => 'Subscribe',
      'access arguments' => array('access content'),
  );
  $items['newsletter/unsubscribe'] = array(
      'title' => 'Unsubscribe',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('pcnewsletters_unsubscribe_form'),
      'access arguments' => array('access content'),
          // 'file' => 'pcnewsletters.forms.inc',
  );
  return $items;
}

/*
  function pcnewsletters_block_info() {
  $blocks['subscribe'] = array(
  'info' => t('Newsletter subscribe'),
  );
  return $blocks;
  }

  function pcnewsletters_block_view($delta = '') {
  module_load_include('inc', 'pcnewsletters', 'pcnewsletters.forms');
  $block['title'] = t('Subscribe');
  $block['content'] = drupal_get_form('pcnewsletters_subscribe_form');
  return $block;
  }
 */

function pcnewsletters_form_pccheckout_checkout_form_alter(&$form, $form_state, $form_id) {
  if (isset($form['personal'])) {
    /* $form['personal']['subscribe'] = array(
      '#type' => 'checkbox',
      '#title' => t('Subscribe to newsletter'),
      );
      array_unshift($form['personal']['submit']['#submit'], 'pcnewsletters_form_pccheckout_form_submit');
     */
  }
}

function pcnewsletters_form_pccheckout_form_submit($form, &$form_state) {
  if (isset($form_state['values']['personal']['subscribe'])) {
    $customer = Customers\Factory::Current();
    if ($customer) {
      /* $subscription = Factory::GetByEmail($customer->email);
        if (!$subscription) {
        $subscription = Factory::Create($customer->email);
        Factory::Save($subscription);
        } */
    }
    //  drupal_set_message(t('Subscribed'));
  }
}

function pcnewsletters_subscribe_form($form, $form_state) {
  $customer = \printconnect\Customers\Factory::Current();
  $email = '';

  if ($customer) {
    $email = $customer->email;
  }

  if (!isset($form_state['storage']['subscribed'])) {

    $form['text'] = array(
        '#type' => 'container',
        '#attributes' => array('class' => array('text')),
        'content' => array(
            '#prefix' => '<p>',
            '#markup' => t('Inscrivez vous et gagnez <span>5 €</span> sur votre prochaine commande'),
            '#suffix' => '</p>',
        ),
    );

    $form['email'] = array(
        '#type' => 'textfield',
        '#title' => t('Email'),
        '#default_value' => $email,
        '#description' => t('Email'),
        '#required' => TRUE,
        '#attributes' => array('class' => array('hint')),
    );
    $form['actions']['submit'] = array(
        '#type' => 'submit',
        '#value' => t('Subscribe'),
        '#ajax' => array(
            'callback' => 'pcnewsletters_subscribe_form_callback',
            'wrapper' => 'pcnewsletters-subscribe-form',
            'method' => 'replace',
            'effect' => 'fade',
            'progress' => array(
                'message' => NULL,
                'type' => NULL,
            ),
        )
    );
  } else {
    $form['confirmation'] = array(
        '#type' => 'container',
        '#attributes' => array('class' => array('confirmation')),
        'content' => array(
            '#markup' => '<p>' . t('Thank you very much for subscribing. Twice a month, you’ll receive the latest promotions and news. Don’t miss out!') . '</p><div class="icone-newsletter"></div><p>Vous avez reçu votre email de bienvenue.</p>',
        ),
    );
    $form['Tracking_news'] = array(
            '#markup' => '<script type="text/javascript" src="http://action.metaffiliation.com/trk.php?mclic=S4ADAB1013&argann='.$form_state['values']['email'].'" ></script>
                            <noscript>
                                <img src="http://action.metaffiliation.com/trk.php?mclic=N4ADAB1013&argann='.$form_state['values']['email'].'" width="1" height="1" border="0" />
                            </noscript>',
    );
   
  }

  $form['#id'] = 'pcnewsletters-subscribe-form';

  return $form;
}

function pcnewsletters_subscribe_form_submit($form, &$form_state) {
//  $subscription = Factory::GetByEmail($form_state['values']['email']);
  // $subscription->EnsureLoaded();
//  if (!$subscription) 
    
    
  try {
    $subscription = Factory::Create($form_state['values']['email']);
    Factory::Save($subscription);
    $form_state['storage']['subscribed'] = TRUE;
     
  } catch (\Exception $ex) {
    
  }

  $form_state['rebuild'] = TRUE;
pcnewsletters_mail_send_client('',$form_state); 
pcnewsletters_mail_send_admin('',$form_state); 
}

function  pcnewsletters_subscribe_form_validate(&$form, &$form_state, $form_id) {
        if (!valid_email_address($form_state['values']['email'])) {
             form_set_error('email', t('You must enter a valid e-mail address.'));
        }
           
}   
function pcnewsletters_subscribe_form_callback($form, $form_state) {
  return $form;
}

function pcnewsletters_unsubscribe_form($form, $form_state) {
  $customer = \printconnect\Customers\Factory::Current();
  $email = '';

  if ($customer) {
    $email = $customer->email;
  }

  $options = array(
      '1' => t('No interest'),
      '2' => t('Too much information'),
  );


  $form['email'] = array(
      '#type' => 'textfield',
      '#title' => t('Email'),
      '#default_value' => $email,
  );

  $form['reason'] = array(
      '#type' => 'radios',
      '#title' => t('Reason'),
      '#options' => $options,
  );

  $form['actions']['submit'] = array(
      '#type' => 'submit',
      '#value' => t('Unsubscribe'),
  );
  return $form;
}

function pcnewsletters_unsubscribe_form_submit($form, $form_state) {
  Factory::Delete($form_state['values']['email']);
  drupal_set_message(t('Unsubscribed'));
}


function pcnewsletters_mail_send_client($form, &$form_state) {
$module = 'pcnewsletters';
$key = 'envoi_email_client';
$to = $form_state['values']['email'];
$from = 'support@flyer.fr';
$params = '<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta charset="UTF-8">
<title>Finissez 2014 en beauté sur Flyer.fr</title>
</head>
<body>
<table border="0" cellpadding="0" cellspacing="0" bgcolor="#f0f0f0">
<tbody>
  <tr>
  <td border="0" width="56" height="50"></td>
  <td border="0" height="50" style="text-align:center;font-size: 11px;line-height: 15px;">
      <font style="color: #808080;">Pour ouvrir cet email dans un navigateur</font>
      <a href="http://flyer.fr/frfr/sites/all/themes/printconnect/flyer/newsletter/week05012015.html" style="color:#4e4e4e;text-decoration: underline;" target="_blank">
        cliquez-ici
      </a>
  </td>
  <td border="0" width="56" height="50"></td></tr>
  <tr>
  <td border="0" width="56"></td>
  <td border="0"> 


<table cellspacing="0" cellpadding="0" border="0" width="618" bgcolor="#f0f0f0" >
<tbody>
  <tr>
      <td bgcolor="#ffffff" width="618" height="10" border="0" style="  border-left: 1px solid #e1e1e1;  border-right: 1px solid #e1e1e1;
    border-radius: 5px 5px 0px 0px;  
    border-top: 1px solid #e1e1e1;  
"></td>
    </tr>
    <tr>
       <td bgcolor="#fff" width="618" height="80" style="  border-left: 1px solid #e1e1e1;  border-right: 1px solid #e1e1e1;
">
     
        <table bgcolor="#ffffff" width="618" height="80" border="0" cellpadding="0">
            <tbody>
              <tr>
                  <td border="0" width="8" style="border:0px;font-family:Arial,Helvetica,sans-serif" height="85"></td>
                  <td valign="top" width="86" height="85" style="border:0px;font-family:Arial,Helvetica,sans-serif">
                      <a target="_blank" href="http://www.flyer.fr"><img height="67" width="85" style="border:0;display:block;" src="https://ci5.googleusercontent.com/proxy/bh-sihJXwe3z-xsx5MpIKUY3hBeJMzc9IrSBT1f7p4DuMZMa1IvYqUt_Cei_YJUCsNt7IRcFlOINa4xE8ZgP6uZwWyMEU8UhlhW2XQnGBUE8bKnuSAD2a69APrE=s0-d-e1-ft#http://d4e7wxbvl20c1.cloudfront.net/images.flyer.fr/emailling/logo.png" border="0"></a>
                  </td>
                  <td width="179" align="right" style="border:0px;font-family:Arial,Helvetica,sans-serif" height="85">
                   <font style="color:#76b700;font-size:20px;font-family:Arial,Helvetica,sans-serif;font-weight: bold;">Inscription réussie à notre newsletter
</font>   
                  </td>
                  <td border="0" width="2" style="border:0px;font-family:Arial,Helvetica,sans-serif" height="85"></td>
              </tr>
            </tbody>
          </table>
       
       </td>
    </tr>
    <tr>
        <td width="618" height="44" style="  border-left: 1px solid #e1e1e1;  border-right: 1px solid #e1e1e1;
">
         
             <table valign="top" width="618" height="44" border="0" align="center" cellpadding="0" cellspacing="0">
                  <tbody>
                        <tr bgcolor="#3c3c3a">
                            <td width="27" height="44" style="border-bottom: 4px solid #ff6600;" border="0"></td>
                            <td width="22" style="border-bottom: 4px solid #ff6600;" height="44"><img height="20" width="22" style="border:0;display:block;" src="http://d4e7wxbvl20c1.cloudfront.net/images.flyer.fr/emailling/bermail/home.jpg"></td>
                            <td width="94" bgcolor="#3c3c3a" style="border-bottom: 4px solid #ff6600;font-family:&rsquo;Open Sans&rsquo;, Arial, sans-serif;" border="0" height="44">
                              <a href="http://www.flyer.fr" style="text-decoration: none;font-size: 13px;color: #ffffff;line-height: 16.52px;font-family: &rsquo;Open Sans&rsquo;, Arial, sans-serif;" target="_blank">
                                <font style="font-weight: 700;text-decoration: none;font-size: 13px;color: #ffffff;line-height: 16.52px;">ACCUEIL</font>
                              </a>
                            </td>
                            
                            <td width="9" style="border-bottom: 4px solid #ff6600;" height="44"><img height="9" width="10" style="border:0;display:block;" src="http://d4e7wxbvl20c1.cloudfront.net/images.flyer.fr/emailling/bermail/point.jpg"></td>
                            <td width="10" border="0" style="border-bottom: 4px solid #ff6600;" height="44"></td>
                            <td width="133" bgcolor="#3c3c3a" style="border-bottom: 4px solid #ff6600; font-family: &rsquo;Open Sans&rsquo;, Arial, sans-serif; font-size: 13px;" border="0" height="44">
                              <a href="http://flyer.fr/nos-produits" style="text-decoration: none;font-size: 13px;color: #ffffff;line-height:16.52px;font-family:&rsquo;Open Sans&rsquo;, Arial, sans-serif;" target="_blank">
                              <font style="font-weight: 700;text-decoration: none;font-size: 13px;color: #ffffff;line-height: 16.52px;">NOS PRODUITS</font>
                            </a></td>
                            
                            <td width="9" style="border-bottom: 4px solid #ff6600;" height="44"><img height="9" width="10" style="border:0;display:block;" src="http://d4e7wxbvl20c1.cloudfront.net/images.flyer.fr/emailling/bermail/point.jpg"></td>
                            <td width="10" border="0" style="border-bottom: 4px solid #ff6600;" height="44"></td>
                            <td width="129" style="border-bottom: 4px solid #ff6600;" border="0" height="44">
                              <a href="http://flyer.fr/cr%C3%A9ations-en-ligne" style="text-decoration: none;font-size: 13px;color: #ffffff;line-height:16.52px;font-family:&rsquo;Open Sans&rsquo;, Arial, sans-serif;" target="_blank">
                              <font style="font-weight: 700;">NOS MOD&Egrave;LES</font>
                              </a>
                            </td>
                            
                            <td width="9" style="border-bottom: 4px solid #ff6600;" height="44"><img height="9" width="10" style="border:0;display:block;" src="http://d4e7wxbvl20c1.cloudfront.net/images.flyer.fr/emailling/bermail/point.jpg"></td>
                            <td width="10" border="0" style="border-bottom: 4px solid #ff6600;" height="44"></td>
                            <td width="132" style="border-bottom: 4px solid #ff6600;font-family:&rsquo;Open Sans&rsquo;, Arial, sans-serif;" border="0" height="44">
                               <a href="http://flyer.fr/categories/commande" style="text-decoration: none;font-size: 13px;color: #ffffff;line-height: 16.52px;font-family:&rsquo;Open Sans&rsquo;, Arial, sans-serif;" target="_blank">
                                <font style="font-weight: 700;"> FAQ </font>
                              </a>
                            </td>
                            <td width="30" border="0" style="border-bottom: 4px solid #ff6600;" height="44"></td>
                        </tr>
                  </tbody>
                  </table> 
        </td>
    </tr>
     
    <tr>
      <td bgcolor="#ffffff" height="17" style="border-right:1px solid #e1e1e1;border-left:1px solid #e1e1e1;">&nbsp;</td>
    </tr>
    <tr>
      <td bgcolor="#fff" style="border-right:1px solid #e1e1e1;border-left:1px solid #e1e1e1;">
        <table border="0" cellspacing="0" cellpadding="0" width="618px">
          <tbody>
              <tr>
              <td width="12">&nbsp; </td>
              <td border="0" height="19" width="16" align="left">
                <img height="14" width="14" style="border:0;display:block;" src="http://d4e7wxbvl20c1.cloudfront.net/images.flyer.fr/lpbonneaffaire/alterbonneaff/pucemail.png">
              </td>
              <td border="0">
                <font style="color:#ff6600;font-size:18px;line-height:16px;font-family:Arial,Helvetica,sans-serif;font-weight:bold;">Bienvenue sur Flyer.fr</font>
              </td>
            <td border="0" width="16"></td>
            </tr>
          </tbody>
        </table>
      </td>
    </tr>
    <tr>
      <td bgcolor="#ffffff" height="15" style="border-right:1px solid #e1e1e1;border-left:1px solid #e1e1e1;">&nbsp;</td>
    </tr>
    <tr>
      <td bgcolor="#ffffff"  style="border-right:1px solid #e1e1e1;border-left:1px solid #e1e1e1;">
        <table border="0" align="center" cellpadding="0" cellspacing="0" width="100%">
          <tbody>
            <tr>
              <td height="12" width="27">&nbsp;</td> 
              <td height="12" width="564" align="left">
                 <font style="color: #444444;font-size: 15px;font-family: Arial,Helvetica,sans-serif;font-weight: normal;letter-spacing: 0.5px;">Nous nous réjouissons de vous compter parmi nos abonnés newsletter. </font><br>
                 <font style="line-height: 23px;color: #444444;font-size: 15px;font-family: Arial,Helvetica,sans-serif;font-weight: normal;letter-spacing: 0.5px;">À partir d\'aujourd\'hui, vous pourrez recevoir nos offres et découvrir toutes les  nouveautés sur notre activité et nos produits.</font>
              </td>
              <td height="12" width="27"></td>
            </tr> 
            <tr>
                <td bgcolor="#ffffff" height="20">&nbsp;</td>
            </tr>
            <tr>
              <td height="12" width="27">&nbsp;</td> 
              <td height="12" width="564" align="left">
                 <font style="color: #444444;font-size: 15px;font-family: Arial,Helvetica,sans-serif;font-weight: letter-spacing: 0.5px;">Nous souhaitons vous remercier de l’intérêt que vous portez à notre site en vous</font><br>
                 <font style="line-height: 23px;color: #444444;font-size: 15px;font-family: Arial,Helvetica,sans-serif;font-weight: normal;letter-spacing: 0.5px;">offrant <strong>5€ de réduction</strong> sur votre prochaine commande.</font><br>
                 <font style="color: #444444;font-size: 15px;font-family: Arial,Helvetica,sans-serif;font-weight: normal;letter-spacing: 0.5px;">Pour en profiter, utilisez le <strong>code promo :</strong> <span style="color: #75b400;font-size: 15px;font-family: Arial,Helvetica,sans-serif;font-weight: bold;">newsflyer2014</span></font>
              </td>
              <td height="12" width="27"></td>
            </tr> 
          </tbody>
        </table>
      </td>
      </tr>
      <tr>
      <td bgcolor="#ffffff" height="20" style="border-right:1px solid #e1e1e1;border-left:1px solid #e1e1e1;">&nbsp;</td>
    </tr>
    <tr>
     <td bgcolor="#ffffff" style="  border-left: 1px solid #e1e1e1;  border-right: 1px solid #e1e1e1;
">
      <table border="0" align="center" cellpadding="0" cellspacing="0">
        <tbody>
          <tr>
            <td width="10" height="249"></td>
            <td width="589" height="249" align="center" border="0"> 
            <a target="_blank" href="http://www.flyer.fr/nos-bonnes-affaires">   
               <img height="249" width="589" style="border:0;display:block;" src="http://d4e7wxbvl20c1.cloudfront.net/images.flyer.fr/logique_pa_logique/mail/img-newslpl1.png"> 
            </a>       
            </td>
            <td width="10" height="249"></td>
          </tr>
        </tbody>
      </table>
     </td>
    </tr>
    <tr>
      <td bgcolor="#ffffff" height="18" style="border-right:1px solid #e1e1e1;border-left:1px solid #e1e1e1;">&nbsp;</td>
    </tr>
    <tr>
      <td bgcolor="#fff" style="border-right:1px solid #e1e1e1;border-left:1px solid #e1e1e1;">
        <table border="0" cellspacing="0" cellpadding="0" width="618px">
          <tbody>
              <tr>
              <td width="12">&nbsp; </td>
              <td border="0" height="19" width="21" align="left">
                <img height="14" width="14" style="border:0;display:block;" src="http://d4e7wxbvl20c1.cloudfront.net/images.flyer.fr/lpbonneaffaire/alterbonneaff/pucemail.png">
              </td>
              <td border="0">
                <font style="color:#ff6600;font-size:18px;line-height:16px;font-family:Arial,Helvetica,sans-serif;font-weight:bold;">Faites de bonnes affaires sur Flyer.fr</font>
              </td>
            <td border="0" width="16"></td>
            </tr>
          </tbody>
        </table>
      </td>
    </tr>
    <tr>
      <td bgcolor="#ffffff" height="20" style="border-right:1px solid #e1e1e1;border-left:1px solid #e1e1e1;">&nbsp;</td>
    </tr> 
      <tr>
        <td bgcolor="#fafafa" height="10"  width="618" style="border-right:1px solid #e1e1e1;border-left:1px solid #e1e1e1;">
          <table border="0" width="618" cellspacing="0" cellpadding="0">
            <tbody>
              <tr>
                <td  height="10" width="617" valign="center" align="center">
              <img src="http://d4e7wxbvl20c1.cloudfront.net/images.flyer.fr/logique_pa_logique/mail/img-triangl.png" height="10" width="617">
                </td>
              </tr>
            </tbody>
          </table>
          
        </td>
      </tr>
      <tr>
        <td bgcolor="#fafafa" height="203" width="590" valign="center" align="center"  style="border-right:1px solid #e1e1e1;border-left:1px solid #e1e1e1;">
            <a href="http://www.flyer.fr/cart/add/%7B%22codes%22%3A%5B%22PDEAL1%22%5D%2C%22items%22%3A%5B%7B%22productPriceGroupId%22%3A8482%2C%22quantity%22%3A1000%2C%22vat%22%3A%220.2100%22%7D%5D%7D" target="_blank">
              <img src="http://d4e7wxbvl20c1.cloudfront.net/images.flyer.fr/logique_pa_logique/mail/img-NSprd1.png" height="203" width="590"></a>
        </td>  
      </tr>
      <tr>
        <td bgcolor="#fafafa" height="13" width="618" style="border-right:1px solid #e1e1e1;border-left:1px solid #e1e1e1;">
        </td>
      </tr>
      <tr>
        <td height="1"  style="border-right:1px solid #e1e1e1;border-left:1px solid #e1e1e1;"> 
          <table border="0" width="618" cellspacing="0" cellpadding="0">
            <tbody>
              <tr>
                <td bgcolor="#fafafa" width="12" height="1" ></td>
                <td bgcolor="#e7e3e3" width="589" height="1" style="border-right:1px solid #e1e1e1;border-left:1px solid #e1e1e1;"></td>
                <td bgcolor="#fafafa" width="12" height="1"></td>
              </tr>
            </tbody>
          </table> 
        </td>
      </tr>
      <tr>
        <td bgcolor="#fafafa" height="5" width="618"  style="border-right:1px solid #e1e1e1;border-left:1px solid #e1e1e1;"></td>
      </tr>
      <tr> 
          <td bgcolor="#fafafa" height="203" width="590" valign="center" align="center"  style="border-right:1px solid #e1e1e1;border-left:1px solid #e1e1e1;">
            <a href="http://www.flyer.fr/cart/add/%7B%22codes%22%3A%5B%22PDEAL2%22%5D%2C%22items%22%3A%5B%7B%22productPriceGroupId%22%3A8781%2C%22quantity%22%3A250%2C%22vat%22%3A%220.2100%22%7D%5D%7D" target="_blank"><img src="http://d4e7wxbvl20c1.cloudfront.net/images.flyer.fr/logique_pa_logique/mail/img-NSprd2.png" height="203" width="590"></a>
          </td> 
      </tr>
      <tr>
        <td bgcolor="#fafafa" height="13" width="618" style="border-right:1px solid #e1e1e1;border-left:1px solid #e1e1e1;">
        </td>
      </tr>
      <tr>
        <td height="1"  style="border-right:1px solid #e1e1e1;border-left:1px solid #e1e1e1;"> 
          <table border="0" width="618" cellspacing="0" cellpadding="0">
            <tbody>
              <tr>
                <td bgcolor="#fafafa" width="12" height="1" ></td>
                <td bgcolor="#e7e3e3" width="589" height="1" style="border-right:1px solid #e1e1e1;border-left:1px solid #e1e1e1;"></td>
                <td bgcolor="#fafafa" width="12" height="1"></td>
              </tr>
            </tbody>
          </table> 
        </td>
      </tr>
      <tr>
        <td bgcolor="#fafafa" height="5" width="618"  style="border-right:1px solid #e1e1e1;border-left:1px solid #e1e1e1;"></td>
      </tr>
      <tr> 
          <td bgcolor="#fafafa" height="203" width="590" valign="center" align="center"  style="border-right:1px solid #e1e1e1;border-left:1px solid #e1e1e1;">
            <a href="http://www.flyer.fr/cart/add/%7B%22codes%22%3A%5B%22PDEAL3%22%5D%2C%22items%22%3A%5B%7B%22productPriceGroupId%22%3A8528%2C%22quantity%22%3A2000%2C%22vat%22%3A%220.2100%22%7D%5D%7D" target="_blank"><img src="http://d4e7wxbvl20c1.cloudfront.net/images.flyer.fr/logique_pa_logique/mail/img-NSprd3.png" height="203" width="590"></a>
          </td> 
      </tr>

   
    <tr>
      <td bgcolor="#fafafa" width="618" height="17" style="  border-left: 1px solid #e1e1e1;  border-right: 1px solid #e1e1e1;
"></td>
    </tr>
    <tr>   
      <td width="618" height="27" align="center" bgcolor="#ff6600" border="0" style="border:0px;font-family:Arial,Helvetica,sans-serif;font-size: 17px;line-height: 20,06px;color: #ffffff;font-weight: bold;text-align: center;">
      <font style="border:0px;font-family:Arial,Helvetica,sans-serif;font-size: 17px;line-height: 20,06px;color: #ffffff;font-weight: bold;text-align: center;">
      Nos avantages
      </font>
      </td>
    </tr>
    <tr>
      <td width="618" height="7" valign="middle" style="
    background-color: #ececec;  border-left: 1px solid #e1e1e1;  border-right: 1px solid #e1e1e1;
"> 
          <img src="http://d4e7wxbvl20c1.cloudfront.net/images.flyer.fr/emailling/imgmailing/img-shadow.png" width="618" height="7" style="border:0;display:block">
      </td>
    </tr> 
    <tr>
    <td width="618" style="background-color:#ececec;border-left: 1px solid #e1e1e1;border-right: 1px solid #e1e1e1;" bgcolor="#ececec">
        <table border="0" width="618" cellspacing="0" cellpadding="0">
          <tbody><tr>
            <td width="139" height="50" align="left" valign="center">
      <a href="http://www.flyer.fr/nos-avantages">
              <img height="50" width="139" style="border:0;display:block;" src="http://d4e7wxbvl20c1.cloudfront.net/images.flyer.fr/emailling/imgmailing/img-menu-1.png">
          </a>
          </td>
            <td width="1" rowspan="2" align="left" valign="middle"> 
              <img src="http://d4e7wxbvl20c1.cloudfront.net/images.flyer.fr/emailling/bermail/separateur.png"> 
            </td>
            <td width="121" height="43" align="right" valign="middle">
            <a href="http://www.flyer.fr/nos-avantages">
              <img height="50" width="125" style="border:0;display:block;" src="http://d4e7wxbvl20c1.cloudfront.net/images.flyer.fr/emailling/imgmailing/img-menu-2.png">
          </a>
          </td>
             <td width="1" rowspan="2" align="left" valign="middle"> 
              <img src="http://d4e7wxbvl20c1.cloudfront.net/images.flyer.fr/emailling/bermail/separateur.png"> 
            </td>
            <td width="117" height="50" align="right" valign="middle">
            <a href="http://www.flyer.fr/nos-avantages">
              <img height="50" width="117" style="border:0;display:block;" src="http://d4e7wxbvl20c1.cloudfront.net/images.flyer.fr/emailling/imgmailing/img-menu-3.png">
            </a>
            </td>
             <td width="1" rowspan="2" align="left" valign="middle"> 
              <img src="http://d4e7wxbvl20c1.cloudfront.net/images.flyer.fr/emailling/bermail/separateur.png"> 
            </td>
            <td width="102" height="50" align="right" valign="middle">
             <a href="http://www.flyer.fr/nos-avantages">
              <img height="50" width="102" style="border:0;display:block;" src="http://d4e7wxbvl20c1.cloudfront.net/images.flyer.fr/emailling/imgmailing/img-menu-4.png">
      </a>
            </td>
            <td width="1" rowspan="2" align="left" valign="middle">
              <img src="http://d4e7wxbvl20c1.cloudfront.net/images.flyer.fr/emailling/bermail/separateur.png"></td>
            <td width="131" height="50" align="right" valign="middle">
            <a href="http://www.flyer.fr/nos-avantages">
              <img height="50" width="131" style="border:0;display:block;" src="http://d4e7wxbvl20c1.cloudfront.net/images.flyer.fr/emailling/imgmailing/icon-menu-5.png">
      </a>
            </td>
          </tr> 
          <tr>
            <td height="25" align="right" valign="text-top" width="125">
              <font style="text-align: center;">
                <a target="_blank" style="color:#646464;font-size:11px;font-family:arial;text-align:center;display:block;text-decoration:none;" href="http://www.flyer.fr/nos-avantages">
                Des impressions de <br> tr&egrave;s haute qualit&eacute;
                </a>
              </font>
            </td>
            <td height="10" align="left" valign="text-top" width="121">
              <font>
                <a target="_blank" style="color:#646464;font-size:11px;font-family:arial;text-align:center;display:block;text-decoration:none;" href="http://www.flyer.fr/nos-avantages">
                  Une livraison ultra <br>rapide
                </a>
              </font>
            </td>
            <td height="10" align="left" valign="text-top" width="117">
              <font>
                <a target="_blank" style="color:#646464;font-size:11px;font-family:arial;text-align:center;display:block;text-decoration:none;" href="http://www.flyer.fr/nos-avantages">
                  Des petits prix
                </a>
              </font>
            </td>
            <td height="10" align="left" valign="text-top" width="102">
              <font>
                <a target="_blank" style="color:#646464;font-size:11px;font-family:arial;text-align:center;display:block;text-decoration:none;/* text-align: center; */" href="http://www.flyer.fr/nos-avantages">
                  Un service <br> rapproch&eacute;
                </a>
              </font>
            </td>
            <td height="10" align="top" valign="text-top" width="116">
              <font>
                <a target="_blank" style="color:#646464;font-size:11px;font-family:arial;text-align:center;display:block;text-decoration:none;" href="http://www.flyer.fr/nos-avantages">
                  Des processus<br> simplifi&eacute;s
                </a>
              </font>
            </td>
          </tr>
        </tbody>
        </table>
      </td>
      </tr>
     
    <tr>
      <td width="618" height="10" style="background-color: #ececec;border-bottom: 1px solid #e1e1e1;border-radius: 0px 0px 5px 5px;border-left: 1px solid #e1e1e1;border-right: 1px solid #e1e1e1;">
      
      </td>
    </tr>
    <tr>
      <td width="618" height="15" bgcolor="#f0f0f0">    
      </td>
    </tr>
 
    <tr>
      <td width="618" height="149" bgcolor="#f0f0f0">
          <table border="0" height="149" width="618" cellspacing="0" cellpadding="0" bgcolor="#FFFFFF" style="background-color: #ffffff;border: 1px solid #e1e1e1;border-radius:5px;">
      <tbody>
        <tr>
          <td width="14" height="22"></td>  
          <td width="456" height="22"></td>
          <td width="132" height="22"></td>
          <td width="14" height="22"></td>
        </tr>
        <tr>
          <td width="14" height="8"></td>  
          <td width="456" height="129" valign="bottom">
            <table border="0" width="456" height="129" cellspacing="0" cellpadding="0">
              <tbody>
                <tr>
                  <td width="253" height="38" valign="top">
                    <img src="http://d4e7wxbvl20c1.cloudfront.net/images.flyer.fr/emailling/imgmailing/img-text-footer.png" width="253" height="33" style="displayblock;border:0">
                  </td>
                </tr>
                <tr>
                  <td width="253" height="19">
                    <table width="100%" height="19" border="0" cellpadding="0" cellspacing="0">
                      <tbody>
                      <tr>
                        <td width="24" height="19" valign="middle"><img width="15" height="14" style="border:0px;display:block;" src="http://d4e7wxbvl20c1.cloudfront.net/images.flyer.fr/emailling/phone.png"></td>
                        <td width="95" height="19" style="font-family:&rsquo;Open Sans&rsquo;, Arial, sans-serif;color:#606060;font-size:13px;line-height:19px;">03 20 38 24 53</td>
                        <td width="24" height="19" valign="middle"><img width="15" height="14" style="border:0px;display:block;" src="http://d4e7wxbvl20c1.cloudfront.net/images.flyer.fr/emailling/mail.png"></td>
                        <td width="253" height="19"><a style="color:#606060;text-decoration:none;font-family:&rsquo;Open Sans&rsquo;, Arial, sans-serif;font-size:13px;" href="mailto:info@Flyer.fr">info@Flyer.fr</a></td>
                      </tr>
                      </tbody>
                    </table>
                  </td>
                </tr>
                <tr>
                  <td width="456" height="72" valign="bottom">
                    <img src="http://d4e7wxbvl20c1.cloudfront.net/images.flyer.fr/emailling/imgmailing/footer-img.png" width="456" height="72" style="displayblock;border:0">
                  </td>
                </tr>
              </tbody>
            </table>
          </td>
          <td width="132" height="129" valign="bottom"><a href="http://www.flyer.fr/"><img width="132" height="129" style="displayblock;border:0" src="http://d4e7wxbvl20c1.cloudfront.net/images.flyer.fr/emailling/imgmailing/footer-logo-flyerfr.png"></a>
          </td>
          <td width="14" height="129"></td>
        </tr>
      </tbody>
    </table>
      </td>
    </tr>
    
    <tr>
      <td width="318" height="17" bgcolor="#f0f0f0"></td>
    </tr>
 <tr bgcolor="#f0f0f0">
  <td height="20" border="0" align="center" style="font-family:Arial,Helvetica,sans-serif" width="630">
    <table border="0" align="center" width="25%">
      <tbody>
        <tr>
           <td border="0" style="border:0px;font-family:Arial,Helvetica,sans-serif">
            <a target="_blank" href="https://www.facebook.com/Flyer.fr">
              <img height="20" width="20" style="border:0;display:block;" src="https://ci6.googleusercontent.com/proxy/0NEFB9LQt7Eu5Uquf_C8XBZWao_mj6azxA3yXWWE28QxcpbU1k2ZVX0xhiR1mBBp8sFT3U7GROo87-kd-Cyx0xmowCkg3YgpQ5ULrGpzMwmj101tmygSrUNiSEWtySP9xl8=s0-d-e1-ft#http://pc-images.s3-eu-west-1.amazonaws.com/images.flyer.fr/emailling/l1.png">
              </a>
            </td>
          <td border="0" style="border:0px;font-family:Arial,Helvetica,sans-serif">
            <a target="_blank" href="https://www.twitter.com/Flyer_fr">
              <img height="20" width="20" style="border:0;display:block;" src="https://ci4.googleusercontent.com/proxy/MGIsjuYK_pBhOQMtkmPTQGgmTAeQtgRgKlQFniToQMna_CLsE4h0fPxqXfR5DiVdOf_efyxn-EeqIzgIX5ZfXBIwuu6xxoB_fElzw0CGyfkjF2qp7z89gn1NiEoDF9K7zLI=s0-d-e1-ft#http://pc-images.s3-eu-west-1.amazonaws.com/images.flyer.fr/emailling/l2.png">
              </a>
            </td>
          <td border="0" style="border:0px;font-family:Arial,Helvetica,sans-serif">
            <a target="_blank" href="https://plus.google.com/+FlyerFr">
              <img height="20" width="20" style="border:0;display:block;" src="https://ci5.googleusercontent.com/proxy/1zMFwsedxij1YThAcXSHg9G_pgmPxQPDWmHmKH4Fu6qHk7pLvPYGbrq56Gf0JvgcUeTK6CM2SKx33KHjXEvuzpHAAs_npN3rypwmQxwN0pJgOB1VHohG3e-Abeaydf8QlAQ=s0-d-e1-ft#http://pc-images.s3-eu-west-1.amazonaws.com/images.flyer.fr/emailling/l3.png">
              </a>
            </td>
          <td border="0" style="border:0px;font-family:Arial,Helvetica,sans-serif">
            <a target="_blank" href="http://www.youtube.com/channel/UCB98N-F-0O5VHavsLRI7_uQ">
              <img height="20" width="20" style="border:0;display:block;" src="https://ci6.googleusercontent.com/proxy/p7OUh4AphqapynFkGg_Dl1IZwlvFJZ715cftaoivjKu2cinavSihJnQnsEK2HZtjKKFcUoRhAQ0qK081f1jA3xnIJR3DlXRyM-10Wyqgq68jo3rHZTqOCzoWdSugqyM0h0g=s0-d-e1-ft#http://pc-images.s3-eu-west-1.amazonaws.com/images.flyer.fr/emailling/l4.png">
              </a>
            </td>
          </tr>
        </tbody>
      </table>
    </td>
</tr>
<tr bgcolor="#f0f0f0">
  <td height="26" align="center" border="0" style="font-family:Arial,Helvetica,sans-serif;color:rgb(153,153,153);font-size:12px" width="630">Si vous ne souhaitez plus recevoir ces messages de la part de
     <a href="http://www.FLYER.FR" target="_blank" style="color:rgb(153,153,153);text-decoration:none;">FLYER.FR</a>, veuillez 
     <a target="_blank" href="http://www.flyer.fr/newsletter/unsubscribe" style="color:#7e7e7e;font-weight: 600;text-decoration:none;">vous d&eacute;sabonner</a>.
  </td>
</tr>
<tr bgcolor="#f0f0f0">
  <td height="24" align="center" border="0" style="font-family:Arial,Helvetica,sans-serif;color:rgb(67,67,67);font-size:12px" width="630">
  &copy; 2014 <a href="http://www.FLYER.FR" target="_blank" style="text-decoration:none;color:rgb(67,67,67);">FLYER.FR</a> | Tous droits r&eacute;serv&eacute;s.
  </td>
</tr>
</tbody>
</table>
  </td>
  <td border="0" width="56" height="19"></td>
  </tr>
  <tr><td border="0" width="56" height="19"></td><td border="0"></td><td border="0" width="56" height="19"></td></tr>
</tbody>
</table>
</body>
</html>
';
$language = language_default();
$send = TRUE;
$result = drupal_mail($module, $key, $to, $language, $params, $from, $send );
$sendMeail = FALSE;
if ($result['result'] == TRUE) {
    $sendMeail = TRUE;
}
// mail info insc NL admin
   
}
function pcnewsletters_mail_send_admin($form, &$form_state){
    $module = 'pcnewsletters';
    $key = 'envoi_email_admin';
    $from = 'support@flyer.fr';
    $parms = '<table valign="top" width="620" border="0px" align="center" cellpadding="0" cellspacing="0">
                                <tr>
                                  <td border="0"  width="30"></td>
                                  <td border="0" >
                                    <font style="font-family:Helvetica,arial;font-size:16px;color:#646464;line-height:16px;"><strong>
                                      Bonjour,</strong></font>
                                  </td>
                                  <td border="0"  width="15"></td> 
                                </tr>
                                <tr height="17px">
                                <td border="0" >&nbsp;</td> <td border="0" >&nbsp;</td> <td border="0" >&nbsp;</td>
                                 </tr>
                                <tr>
                                  <td border="0"  height="48"></td>
                                  <td border="0" >
                                    <font style="font-family:Helvetica,arial;font-size:14px;color:#646464;line-height:16px;"><strong>
                                        Un nouveau client vient de déposer une incription newsletter sur le site <a style="color:#ff6600;" href="www.flyer.fr/frfr">Flyer.fr</a>.<br> 
                                   </strong></font><br>
                 <font style="font-family:Helvetica,arial;font-size:15px;color:#646464;line-height:16px;">
                                      Détail d\'infos :<br>
                                    </font>
                                 <p><br/><b>' . t('Email') . '</b>: '. $form_state['values']['email'].'<br/></p>
                                </td>
                                  <td border="0" ></td> 
                             </tr>
                                <tr height="17px">
                                <td border="0" >&nbsp;</td> <td border="0" >&nbsp;</td> <td border="0" >&nbsp;</td>
                                 </tr>
                                <tr>
                                  <td border="0"  width="14"></td>
                                  <td border="0" >

                                  </td>
                                  <td border="0"  width="15"></td> 
                                </tr>

                            </table>';
    $language = language_default();
    $send = TRUE;
    $result = drupal_mail($module, $key, variable_get('pcnewsletters', 'contact@flyer.fr , contact@agenceoneo.com '), language_default(), $parms, $from, $send);
    $sendMeailAdmin = FALSE;
    if ($result['result'] == TRUE) {
        $sendMeailAdmin = TRUE;
    }
}

 function pcnewsletters_mail($key, &$message, $params) {
  switch ($key) {
    case 'envoi_email_client':
          $message['headers']['Content-Type'] = 'text/html; charset=UTF-8; format=flowed';         
          $message['subject'] =  t('Newsletter Flyer.fr');
          $message['body'][] = $params;
        break;
    case 'envoi_email_admin':
          $message['headers']['Content-Type'] = 'text/html; charset=UTF-8; format=flowed';
          $message['subject'] =  t('Newsletter Flyer.fr');
          $message['body'][] = $params;
        break;
  
  }
}