<?php

use \printconnect\Newsletters\Subscriptions\Factory;
use \printconnect\Customers;

function pcnewsletters_menu() {
  $items['newsletter'] = array(
      'title' => 'Newsletter',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('pcnewsletters_subscribe_form'),
      'access arguments' => array('access content'),
          //'file' => 'pcnewsletters.forms.inc',
  );
  $items['newsletter/subscribe'] = array(
      'title' => 'Subscribe',
      'access arguments' => array('access content'),
  );
  $items['newsletter/unsubscribe'] = array(
      'title' => 'Unsubscribe',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('pcnewsletters_unsubscribe_form'),
      'access arguments' => array('access content'),
          // 'file' => 'pcnewsletters.forms.inc',
  );
  return $items;
}

/*
  function pcnewsletters_block_info() {
  $blocks['subscribe'] = array(
  'info' => t('Newsletter subscribe'),
  );
  return $blocks;
  }

  function pcnewsletters_block_view($delta = '') {
  module_load_include('inc', 'pcnewsletters', 'pcnewsletters.forms');
  $block['title'] = t('Subscribe');
  $block['content'] = drupal_get_form('pcnewsletters_subscribe_form');
  return $block;
  }
 */

function pcnewsletters_form_pccheckout_checkout_form_alter(&$form, $form_state, $form_id) {
  if (isset($form['personal'])) {
    /* $form['personal']['subscribe'] = array(
      '#type' => 'checkbox',
      '#title' => t('Subscribe to newsletter'),
      );
      array_unshift($form['personal']['submit']['#submit'], 'pcnewsletters_form_pccheckout_form_submit');
     */
  }
}

function pcnewsletters_form_pccheckout_form_submit($form, &$form_state) {
  if (isset($form_state['values']['personal']['subscribe'])) {
    $customer = Customers\Factory::Current();
    if ($customer) {
      /* $subscription = Factory::GetByEmail($customer->email);
        if (!$subscription) {
        $subscription = Factory::Create($customer->email);
        Factory::Save($subscription);
        } */
    }
    //  drupal_set_message(t('Subscribed'));
  }
}

function pcnewsletters_subscribe_form($form, $form_state) {
  $customer = \printconnect\Customers\Factory::Current();
  $email = '';

  if ($customer) {
    $email = $customer->email;
  }

  if (!isset($form_state['storage']['subscribed'])) {

    $form['text'] = array(
        '#type' => 'container',
        '#attributes' => array('class' => array('text')),
        'content' => array(
            '#prefix' => '<p>',
            '#markup' => t('Do you want to learn more about what printconnect.com can do for you?'),
            '#suffix' => '</p>',
        ),
    );

    $form['email'] = array(
        '#type' => 'textfield',
        '#title' => t('Email'),
        '#default_value' => $email,
        '#description' => t('Email'),
        '#required' => TRUE,
        '#attributes' => array('class' => array('hint')),
    );
    $form['actions']['submit'] = array(
        '#type' => 'submit',
        '#value' => t('Subscribe'),
        '#ajax' => array(
            'callback' => 'pcnewsletters_subscribe_form_callback',
            'wrapper' => 'pcnewsletters-subscribe-form',
            'method' => 'replace',
            'effect' => 'fade',
            'progress' => array(
                'message' => NULL,
                'type' => NULL,
            ),
        )
    );
  } else {
    $form['confirmation'] = array(
        '#type' => 'container',
        '#attributes' => array('class' => array('confirmation')),
        'content' => array(
            '#markup' => '<p>' . t('Thank you very much for subscribing. Twice a month, you’ll receive the latest promotions and news. Don’t miss out!') . '</p><div class="icone-newsletter"></div><p>Vous avez reçu votre email de bienvenue.</p>',
        ),
    );
  }

  $form['#id'] = 'pcnewsletters-subscribe-form';

  return $form;
}

function pcnewsletters_subscribe_form_submit($form, &$form_state) {
//  $subscription = Factory::GetByEmail($form_state['values']['email']);
  // $subscription->EnsureLoaded();
//  if (!$subscription) 
  try {
    $subscription = Factory::Create($form_state['values']['email']);
    Factory::Save($subscription);
    $form_state['storage']['subscribed'] = TRUE;
    pcnewsletters_mail_subscribe($form_state['values']['email']);
    
  } catch (\Exception $ex) {
    
  }

  $form_state['rebuild'] = TRUE;
  // }
  //drupal_set_message(t('Subscribed'));
}
function  pcnewsletters_subscribe_form_validate(&$form, &$form_state, $form_id) {
        if (!valid_email_address($form_state['values']['email'])) {
             form_set_error('email', t('You must enter a valid e-mail address.'));
        }
           
}   
function pcnewsletters_subscribe_form_callback($form, $form_state) {
  return $form;
}

function pcnewsletters_unsubscribe_form($form, $form_state) {
  $customer = \printconnect\Customers\Factory::Current();
  $email = '';

  if ($customer) {
    $email = $customer->email;
  }

  $options = array(
      '1' => t('No interest'),
      '2' => t('Too much information'),
  );


  $form['email'] = array(
      '#type' => 'textfield',
      '#title' => t('Email'),
      '#default_value' => $email,
  );

  $form['reason'] = array(
      '#type' => 'radios',
      '#title' => t('Reason'),
      '#options' => $options,
  );

  $form['actions']['submit'] = array(
      '#type' => 'submit',
      '#value' => t('Unsubscribe'),
  );
  return $form;
}

function pcnewsletters_unsubscribe_form_submit($form, $form_state) {
  Factory::Delete($form_state['values']['email']);
  drupal_set_message(t('Unsubscribed'));
}
function pcnewsletters_mail_subscribe($email){
    
     if( $email ){

    
        $body ='<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Document sans nom</title>
</head>

<body>
<style>
td{
	border:0px;
	font-family:Arial, Helvetica, sans-serif;
	}
</style>

<table width="618px" border="" cellpadding="0" cellspacing="0" style="background-color:#fff;border:0px;width:618px;margin:0px auto;">
  <tr >
    <td >
    <table valign="top" width="620" border="0" align="center" cellpadding="0" cellspacing="0">
                <tr>
                  <td>
                    <a style="text-decoration:none;" target="_blank" href=""><img width="140" height="49" style="display:block;border:0;" border="0" src="http://d4e7wxbvl20c1.cloudfront.net/images.flyer.fr/emailling/home.jpg"></a>
                  </td>
                  <td>
                    <a style="text-decoration:none;" target="_blank" href=""><img width="154" height="49" style="display:block;border:0;" border="0" src="http://d4e7wxbvl20c1.cloudfront.net/images.flyer.fr/emailling/nosprod.jpg"></a>
                  </td>
                  <td>
                    <a style="text-decoration:none;" target="_blank" href=""><img width="146" height="49" style="display:block;border:0;" border="0" src="http://d4e7wxbvl20c1.cloudfront.net/images.flyer.fr/emailling/nosmodel.jpg"></a>
                  </td>
                  <td>
                    <a style="text-decoration:none;" target="_blank" href=""><img width="181" height="49" style="display:block;border:0;" border="0" src="http://d4e7wxbvl20c1.cloudfront.net/images.flyer.fr/emailling/bonneaffaire.jpg"></a>
                  </td> 
                </tr>
            </table>
    </td>
  </tr> 
  
 
 <tr height="15px">
    <td >&nbsp;</td>
  </tr> 
  <tr>
 <td style="">
 
<table style="border:0px;" valign="top" width="620" border="0" align="center" cellpadding="0" cellspacing="0">
                <tbody>
              
                <tr>
                  <td height="15" width="30px"></td>
                  <td>
                    <font style="font-family:Helvetica,arial;font-size:16px;color:#646464;line-height:18px;"><strong>
                   Nous vous remercions de l\'intérêt que vous portez à Flyer.fr et de votre inscription à notre newsletter.</strong></font>

                  </td>
                  <td></td> 
                </tr>
                <tr height="17px">
                <td >&nbsp;</td> <td>&nbsp;</td> <td>&nbsp;</td>
                 </tr>
                <tr>
                  <td width="14"></td>
                  <td style="font-family:Helvetica,arial;font-size:15px;color:#646464;line-height:18px;">À partir d\'aujourd\'hui, vous pourrez recevoir nos offres et découvrir toutes  les<br /> nouveautés sur notre activité et nos produits.</td>
                  <td width="15"></td> 
                </tr>
 
                <tr>
                 <tr height="15px">
                <td >&nbsp;</td> <td>&nbsp;</td> <td>&nbsp;</td>
                 </tr>
               
            </tbody></table> 
 
 </td>
 </tr>
  
   <tr>
 
  <td align="center">
<table align="center" width="100%" border="0" style="border:0px;">
  <tr>
    <td width="51%" height="322" align="center"><img src="http://d4e7wxbvl20c1.cloudfront.net/images.flyer.fr/emailling/im1.jpg" />	</td>
    <td align="center" width="48%"><img src="http://d4e7wxbvl20c1.cloudfront.net/images.flyer.fr/emailling/im2.jpg" /></td>
   
  </tr>
  <tr>
    <td align="center"><img src="http://d4e7wxbvl20c1.cloudfront.net/images.flyer.fr/emailling/im3.jpg" /></td>
    <td align="center"><img src="http://d4e7wxbvl20c1.cloudfront.net/images.flyer.fr/emailling/im4.jpg" /></td>
    
  </tr>
  
  
  <tr height="15px">
                <td >&nbsp;</td> <td>&nbsp;</td> <td width="1%">&nbsp;</td>
                 </tr> 
  
</table>
 
  	 
   	
    	
 </td>
 
 
  </tr>
    <tr>
 <td>
 	<img src="http://d4e7wxbvl20c1.cloudfront.net/images.flyer.fr/emailling/block.jpg" />
 </td>
  </tr>
</table>

 </body>
</html>';

        $my_module = 'pcnewsletters';
        $my_mail_token = microtime();
        
        $system = drupal_mail_system($my_module, $my_mail_token);
        
        $from = variable_get('system_mail', 'support@flyer.fr');
       
    // info mail 
        $to = variable_get('system_mail', $email );
        $message = array(
            'id' => $my_module . '_' . $my_mail_token,
            'to' => $to,
            'subject' => 'Demande de rappel - Mail de confirmation',
            'body' => array($body),
            'headers' => array(
                'From' => $from,
                'Sender' => $from,
                'Return-Path' => $from,
                'MIME-Version' => '1.0',
                'Content-Type' => 'text/html; charset=UTF-8; format=flowed',
                'Content-Transfer-Encoding' => '8Bit',
                'X-Mailer' => 'Drupal',
            ),
        );
       
        $message = $system->format($message);
        $system->mail($message);   

        if ($system->mail($message)) {
           return true;
        } else {
           return false;
        }

        }else{ return false;}
    
    
    
}