<?php

	/**
	* Implements hook_block_info().
	*/
	function pcstaticproducts_block_info() {
		$blocks = array();
		$blocks['pc_static_products'] = array(
			'info' => t('Static Products'),
			'visibility' => 1,
			'pages' => 'cart',
			'region' => 'content',
			'weight' => 13,
			);
		return $blocks;
	}

	/**
	* Implements hook_block_view().
	*/
	function pcstaticproducts_block_view($delta='') {
		$block = array();
		switch ($delta) {
			case 'pc_static_products':
				$block['subject'] = '';
				$block['content'] = array( '#theme' => 'pcstaticproducts_block', );
				break;
		}
		return $block;
	}

	/**
	* Implements hook_theme().
	*/
	function pcstaticproducts_theme($existing, $type, $theme, $path){
		return array(
			'pcstaticproducts_block' => array(
				'template' => 'static-products',
			),
		);
	}
