<?php

use printconnect\Diagnostics\Debug;
use printconnect\Drupal\Forms;
use printconnect\Drupal\Functions;

/**
 * Implements hook_menu
 *
 * Urls
 */

function pccontact_init() {
  //  drupal_add_js(drupal_get_path('module', 'pccontact') . '/popup_ajax.js');
}
function pccontact_perm () {
  return array('access pccontact',);
}
function pccontact_menu() {
  $items['mailme/%/%'] = array(
      'title' => 'Mail me',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('pccontact_mailme_form', 1, 2),
      'access arguments' => array('access content'),
  );

  $items['mailme/%/%/success'] = array(
      'title' => 'Mail me',
      'page callback' => 'pccontact_success',
      'page arguments' => array(1, 2),
      'access arguments' => array('access content'),
  );
  $items['callmeback/%/%/success'] = array(
      'title' => 'Call me back',
      'page callback' => 'pccontact_success',
      'page arguments' => array(1, 2),
      'access arguments' => array('access content'),
  );
    $items['callmeback/%/%'] = array(
      'title' => 'Call me back',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('pccontact_callmeback_form', 1, 2),
      'access arguments' => array('access content'),
  );
  $items['contact/%'] = array(
      'title' => 'Contact',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('pccontact_contact_form', 1),
      'access arguments' => array('access content'),
  );
 
  $items['contact/general'] = array(
      'page callback' => 'drupal_get_form',
      'page arguments' => array('pccontact_general_form', 1),
      'access arguments' => array('access content'),
      'file' => 'pccontact.forms.inc',
  );
   $items['popup/sendmail'] = array(
      'title' => 'Send mail test',
      'page callback' => 'sendmail',
      'access arguments' => array('access content'),
  );
   $items['popup/ajax'] = array(
        'page callback' => 'ajax_back',
        'access callback' => TRUE,	
        'access arguments' => array('access content'),		
        'type' => MENU_CALLBACK		
    );
   
   
  $items['contact/stores'] = array(
      'title' => 'Contact',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('pccontact_stors_form'),
      'access arguments' => array('access content'),
      'file' => 'pccontact.forms.inc',
  );
   $items['contact/email'] = array(
      'title' => 'Contact',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('pccontact_email_form'),
      'access arguments' => array('access content'),
      'file' => 'pccontact.forms.inc',
  );


  return $items;
}

/*
 * Implements hook_block_info
 * Defines the available blocks
 */

function pccontact_block_info() {
//  $blocks['contact'] = array(
//      'info' => t('Contact block'),
//      'cache' => DRUPAL_CACHE_GLOBAL,
//  );
//  return $blocks;
  return array();
}

/*
 * Implements hook_block_view
 * Implements the available blocks
 */

function pccontact_block_view($delta = '') {
  switch ($delta) {
    case 'contact2':
      $block['title'] = t('Contact');
      $block['content'] = array(
          'text' => array(
              '#markup' => t('About  contacting us'),
          ),
          'link' => array(
              '#markup' => l('Contact us', 'contact/callmeback', array('attributes' => array('class' => array('fancybox', 'iframe')), 'query' => array('contentonly' => TRUE))),
          ),
      );

      return $block;
  }
}

/**
 * Defines the mailme form
 */
function pccontact_mailme_form($form, &$form_state, $idName, $userName) {

  $customer = \printconnect\Customers\Factory::Current();

  drupal_set_title(t('Mail @contact', array('@contact' => $userName)));
  $iconPath = '/images/ww-' . $idName . '.png';
  $form['image'] = array(
      '#type' => 'item',
      '#markup' => theme(
              'image', array(
          'path' => variable_get('file_' . file_default_scheme() . '_path', conf_path() . '/files') . $iconPath
              )
      ),
  );

  $form['title'] = array(
      '#type' => 'item',
      '#prefix' => '<h4>',
      '#suffix' => '</h4>',
      '#markup' => t('Mail @contact', array('@contact' => $userName)),
  );

  $form['name'] = array(
      '#type' => 'textfield',
      '#title' => t('Name'),
      '#required' => TRUE,
      '#default_value' => $customer ? $customer->name : '',
      '#size' => 25,
  );

  $form['email'] = array(
      '#type' => 'textfield',
      '#title' => t('E-mail'),
      '#required' => TRUE,
      '#default_value' => $customer ? $customer->email : '',
      '#size' => 25,
  );

  $form['comment'] = array(
      '#type' => 'textarea',
      '#title' => t('Comment'),
      '#required' => TRUE,
      '#resizable' => FALSE,
  );

  $form['captcha'] = array(
      '#type' => 'captcha',
  );

  $form['submit'] = array(
      '#type' => 'submit',
      '#value' => t('Submit'),
      '#attributes' => array('class' => array('button', 'large', 'submit')),
  );

  return $form;
}

function pccontact_mailme_form_validate($form, &$form_state) {
  /*
    if ($form_state['values']['name'] === NULL) {
    form_set_error('name', t('Name can\'t be empty'));
    }
    if ($form_state['values']['email'] === NULL) {
    form_set_error('email', t('E-mail can\'t be empty'));
    }
    if ($form_state['values']['comment'] === NULL) {
    form_set_error('comment', t('Comment can\'t be empty'));
    }
   */
  if (!valid_email_address($form_state['values']['email'])) {
    form_set_error('email', t('E-mail address is not valid'));
  }
}

function pccontact_mailme_form_submit($form, &$form_state) {
  $params = array();
  $params['account'] = $form_state['values']['email'];
  $params['name'] = $form_state['values']['name'];
  $params['comment'] = $form_state['values']['comment'];
  $params['contact'] = $form_state['build_info']['args']['1'];
  drupal_mail(
          'pccontact', 'mailme', variable_get('pccontact_email', 'info@printconcept.com'), NULL, $params
  );
  //drupal_set_message(t('Your request has been successfully sent'));
  $query = $_GET;
  unset($query['q']);
  drupal_goto('mailme/' . $form_state['build_info']['args']['0'] . '/' . $form_state['build_info']['args']['1'] . '/success', array('query' => $query));
}

/**
 * Defines the callmeback form
 */
function pccontact_callmeback_form($form, &$form_state, $idName, $userName) {
  $customer = \printconnect\Customers\Factory::Current();
  drupal_set_title(t('Have @contact call me back', array('@contact' => $userName)));
  $iconPath = '/images/ww-' . $idName . '.png';
  $form['image'] = array(
      '#type' => 'item',
      '#markup' => theme(
              'image', array(
          'path' => variable_get('file_' . file_default_scheme() . '_path', conf_path() . '/files') . $iconPath
              )
      ),
  );

  $form['title'] = array(
      '#type' => 'item',
      '#prefix' => '<h4>',
      '#suffix' => '</h4>',
      '#markup' => t('Have @contact call me back', array('@contact' => $userName)),
  );

  $form['name'] = array(
      '#type' => 'textfield',
      '#title' => t('Name'),
      '#required' => TRUE,
      '#default_value' => $customer ? $customer->name : '',
      '#size' => 25,
  );

  $form['phone'] = array(
      '#type' => 'textfield',
      '#title' => t('Phone'),
      '#required' => TRUE,
      '#default_value' => $customer ? $customer->phone : '',
      '#size' => 25,
  );

  $form['comment'] = array(
      '#type' => 'textarea',
      '#title' => t('Comment'),
      '#required' => TRUE,
      '#resizable' => FALSE,
  );

  $form['captcha'] = array(
      '#type' => 'captcha',
  );

  $form['submit'] = array(
      '#type' => 'submit',
      '#value' => t('Submit'),
      '#attributes' => array('class' => array('button', 'large', 'submit')),
  );

  return $form;
}

function pccontact_callmeback_form_validate($form, &$form_state) {
  /* if ($form_state['values']['name'] === NULL) {
    form_set_error('name', t('Name can\'t be empty'));
    }
    if ($form_state['values']['phone'] === NULL) {
    form_set_error('email', t('E-mail can\'t be empty'));
    }
    if ($form_state['values']['comment'] === NULL) {
    form_set_error('comment', t('Comment can\'t be empty'));
    } */
}

function pccontact_callmeback_form_submit($form, &$form_state) {
  $params = array();
  $params['phone'] = $form_state['values']['phone'];
  $params['name'] = $form_state['values']['name'];
  $params['comment'] = $form_state['values']['comment'];
  $params['contact'] = $form_state['build_info']['args']['1'];
  drupal_mail(
          'pccontact', 'callmeback', variable_get('pccontact_email', 'info@printconcept.com'), NULL, $params
  );
  //drupal_set_message(t('Your request has been successfully sent'));
  $query = $_GET;
  unset($query['q']);
  drupal_goto('callmeback/' . $form_state['build_info']['args']['0'] . '/' . $form_state['build_info']['args']['1'] . '/success', array('query' => $query));
}

function pccontact_mail($key, &$message, $params) {
  global $language;
  $message['headers']['Content-Type'] = 'text/html; charset=UTF-8; format=flowed';

  switch ($key) {
    case 'mailme':
      $message['subject'] = t('Contact') . ' ' . $params['contact'];
      $message['body'][] = t(
              'Contact !name', array(
          '!name' => $params['name']
              )
      );
      $message['body'][] = $params['account'];
      $message['body'][] = $params['comment'];
      break;
    case 'callmeback':
      $message['subject'] = t('Contact') . ' ' . $params['name'];

      //$message['body'][] = t('Contact !name', array('!name' => $params['name']));
      $message['body'][] = '<br/><b>' . t('Contact') . '</b>: ';
      $message['body'][] = $params['name'];
      $message['body'][] = '<br/><b>' . t('Phone') . '</b>: ';
      $message['body'][] = $params['phone'];
      if (isset($params['email'])) {
        $message['body'][] = '<br/><b>' . t('Email') . '</b>: ';
        $message['body'][] = $params['email'];
      }
      $message['body'][] = '<br/><b>' . t('Comment') . '</b>: <br/>';
      $message['body'][] = nl2br(htmlentities($params['comment']));
      break;

    case 'general':
      $message['subject'] = t('Contact') . ' ' . $params['name'];

      //$message['body'][] = t('Contact !name', array('!name' => $params['name']));
      $message['body'][] = '<br/><b>' . t('Contact') . '</b>: ';
      $message['body'][] = $params['name'];
      $message['body'][] = '<br/><b>' . t('Phone') . '</b>: ';
      $message['body'][] = $params['phone'];
      if (isset($params['email'])) {
        $message['body'][] = '<br/><b>' . t('Email') . '</b>: ';
        $message['body'][] = $params['email'];
      }
      $message['body'][] = '<br/><b>' . t('Comment') . '</b>: <br/>';
      $message['body'][] = nl2br(htmlentities($params['comment']));
      break;
    case 'stores':
          
    $message['subject'] = t('Store subscription') . ' ' . $params['name'];
      $message['body'][] = '<br/><b>' . t('Contact') . '</b>: ';
            $message['body'][] = $params['name'];
            $message['body'][] = '<br/><b>' . t('Phone') . '</b>: ';
            $message['body'][] = $params['phone'];
            if (isset($params['email'])) {
                $message['body'][] = '<br/><b>' . t('Email') . '</b>: ';
                $message['body'][] = $params['email'];
            }
            $message['body'][] = '<br/><b>' . t('socity') . '</b>: ';
            $message['body'][] = $params['socity'];
            $message['body'][] = '<br/><b>' . t('activity') . '</b>: ';
            $message['body'][] = $params['activity'];
            $message['body'][] = '<br/><b>' . t('vatnumber') . '</b>: ';
            $message['body'][] = $params['vatnumber'];

            $message['body'][] = '<br/><b>' . t('Comment') . '</b>: <br/>';
            $message['body'][] = nl2br(htmlentities($params['comment']));
      break;
    case 'cobranding':
      $message['subject'] = 'Cobranding info request';

      $message['body'][] = $params['name'];
      $message['body'][] = $params['email'];
      $message['body'][] = $params['phone'];
      $message['body'][] = $params['comment'];
      break;
    case 'contactfooter':
      $message['subject'] = 'contactformulier via footer';

      $message['body'][] = $params['name'];
      $message['body'][] = $params['email'];
      $message['body'][] = $params['phone'];
      $message['body'][] = $params['comment'];
      break;
    case 'email':
      $message['subject'] = 'Email';
      $message['body'][] = 'test';
      break;
  }

  $message['body'][] = '<br/><b>' . t('Site') . '</b>: ';
  $message['body'][] = $_SERVER['HTTP_HOST'];
  $message['body'][] = '<br/><b>' . t('Language') . '</b>: ';
  $message['body'][] = $language->language;
}

function pccontact_success($idName, $userName) {
  //drupal_add_js('jQuery(document).ready(function () { parent.jQuery.fancybox.close(); });', 'inline');
  $content = array();

  $iconPath = '/images/ww-' . $idName . '.png';
  $content['image'] = array(
      '#type' => 'item',
      '#markup' => theme(
              'image', array(
          'path' => variable_get('file_' . file_default_scheme() . '_path', conf_path() . '/files') . $iconPath
              )
      ),
  );

  $content['name'] = array(
      '#type' => 'item',
      '#prefix' => '<h4>',
      '#suffix' => '</h4>',
      '#markup' => $userName,
  );

  $content['title'] = array(
      '#type' => 'item',
      '#markup' => t('I`ll contact you as soon as possible'),
  );


  return $content;
}

function pccontact_contact_form($form, $form_state, $key) {
  if (!$form_state['rebuild']) {

    $customer = \printconnect\Customers\Factory::Current();
    $form['name'] = array(
        '#type' => 'textfield',
        '#title' => t('Name'),
        '#required' => TRUE,
        '#default_value' => $customer ? $customer->name : '',
    );
    $form['email'] = array(
        '#type' => 'textfield',
        '#title' => t('Email'),
        '#required' => FALSE,
        '#default_value' => $customer ? $customer->email : '',
    );
    $form['phone'] = array(
        '#type' => 'textfield',
        '#title' => t('Phone'),
        '#required' => TRUE,
        '#default_value' => $customer ? $customer->phone : '',
    );
    $form['actions']['submit'] = array(
        '#type' => 'submit',
        '#value' => t('Send'),
        '#attributes' => array('class' => array('noreplace')),
        '#ajax' => array(
            'callback' => 'pccontact_contact_form_callback',
            'wrapper' => 'pccontact-contact-form',
            'method' => 'replace',
            'effect' => 'fade',
        ),
    );
  } else {/*
    $form['result'] = array(
    '#type' => 'container',
    '#attributes' => array('class' => array('box', 'messages', 'status')),
    );
    $form['result']['text'] = array(
    '#markup' => t('Your message has been sent.')
    ); */
  }

  $form['#id'] = 'pccontact-contact-form';
  return $form;
}

function pccontact_contact_form_validate($form, &$form_state) {
  if (!valid_email_address($form_state['values']['email'])) {
    form_set_error('email', t('E-mail address is not valid'));
  }
}

function pccontact_contact_form_submit($form, &$form_state) {
  $params = array();
  $params['phone'] = $form_state['values']['phone'];
  $params['email'] = $form_state['values']['email'];
  $params['name'] = $form_state['values']['name'];
  $key = $form_state['build_info']['args']['0'];

  drupal_mail('pccontact', $key, variable_get('pccontact_email', 'info@printconcept.com'), NULL, $params);
  drupal_set_message(t('Your message has been sent.'));
  $form_state['rebuild'] = TRUE;
}

function pccontact_contact_form_callback($form, &$form_state) {
  return $form;
}

function ajax_back(){
    
      if( isset($_GET['nom']) && !empty($_GET['nom']) ){
          
            $bodyClt = '<table valign="top" width="620" border="0" align="center" cellpadding="0" cellspacing="0">
                                <tr>
                                  <td width="30"></td>
                                  <td>
                                    <font style="font-family:Helvetica,arial;font-size:16px;color:#646464;line-height:16px;"><strong>
                                      Bonjour '.$_GET['nom'].' '.$_GET['prenom'].',</strong></font>
                                  </td>
                                  <td width="15"></td> 
                                </tr>
                                <tr height="17px">
                                <td>&nbsp;</td> <td>&nbsp;</td> <td>&nbsp;</td>
                                 </tr>
                                <tr>
                                  <td height="48"></td>
                                  <td>
                                    <font style="font-family:Helvetica,arial;font-size:14px;color:#646464;line-height:16px;"><strong>
                                   Nous vous remercions  de l’intérêt que vous portez à notre site <a style="color:#ff6600;" href="www.flyer.fr">Flyer.fr</a>.<br> 
                                   </strong></font><br>
                 <font style="font-family:Helvetica,arial;font-size:15px;color:#646464;line-height:16px;">
                                      Votre demande de rappel a bien été prise en compte.<br>
                Un conseiller Flyer.fr va prendre contact avec vous.</font>
                                  </td>
                                  <td></td> 
                             </tr>
                                <tr height="17px">
                                <td>&nbsp;</td> <td>&nbsp;</td> <td>&nbsp;</td>
                                 </tr>
                                <tr>
                                  <td width="14"></td>
                                  <td>

                                  </td>
                                  <td width="15"></td> 
                                </tr>

                            </table>';
            
            $bodyAdmin =  '<table valign="top" width="620" border="0" align="center" cellpadding="0" cellspacing="0">
                                <tr>
                                  <td width="30"></td>
                                  <td>
                                    <font style="font-family:Helvetica,arial;font-size:16px;color:#646464;line-height:16px;"><strong>
                                      Bonjour,</strong></font>
                                  </td>
                                  <td width="15"></td> 
                                </tr>
                                <tr height="17px">
                                <td>&nbsp;</td> <td>&nbsp;</td> <td>&nbsp;</td>
                                 </tr>
                                <tr>
                                  <td height="48"></td>
                                  <td>
                                    <font style="font-family:Helvetica,arial;font-size:14px;color:#646464;line-height:16px;"><strong>
                                        Un nouveau client vient de déposer une demande sur le site <a style="color:#ff6600;" href="www.flyer.fr">Flyer.fr</a>.<br> 
                                   </strong></font><br>
                 <font style="font-family:Helvetica,arial;font-size:15px;color:#646464;line-height:16px;">
                                      Détail d\'infos :<br>
                                    </font>
                                 <p><br/><b>' . t('Contact') . '</b>: '. $_GET['nom'].' '.$_GET['prenom'].'<br/><b>' . t('Téléphone') . '</b>: '.$_GET['phone'].'<br/><b>E-mail</b>: '.$_GET['email'].'<br/></p>
                                </td>
                                  <td></td> 
                             </tr>
                                <tr height="17px">
                                <td>&nbsp;</td> <td>&nbsp;</td> <td>&nbsp;</td>
                                 </tr>
                                <tr>
                                  <td width="14"></td>
                                  <td>

                                  </td>
                                  <td width="15"></td> 
                                </tr>

                            </table>';
        
        
    $bodyHeader  = '<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN">
                <html>
                  <head>
                    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
                    <title>Mail bienvenue inscription</title>
                  </head>
                  <style>
                    img{border:0px !important}
                    a{text-decoration:none;}
                    table{font-family: arial;}
                  </style>
                  <body bgcolor="#ffffff" style="background-color:#ffffff;">
                    <table valign="top" width="620" border="0" align="center" cellpadding="0" cellspacing="0">
                      <tr>
                        <td>
                            <table valign="top" width="620" border="0" align="center" cellpadding="0" cellspacing="0">
                                <tr>
                                  <td>
                                    <a style="text-decoration:none;" target="_blank" href=""><img width="140" height="49" style="display:block;border:0;" border="0" src="http://d4e7wxbvl20c1.cloudfront.net/images.flyer.fr/emailling/home.jpg"></a>
                                  </td>
                                  <td>
                                    <a style="text-decoration:none;" target="_blank" href=""><img width="154" height="49" style="display:block;border:0;" border="0" src="http://d4e7wxbvl20c1.cloudfront.net/images.flyer.fr/emailling/nosprod.jpg"></a>
                                  </td>
                                  <td>
                                    <a style="text-decoration:none;" target="_blank" href=""><img width="146" height="49" style="display:block;border:0;" border="0" src="http://d4e7wxbvl20c1.cloudfront.net/images.flyer.fr/emailling/nosmodel.jpg"></a>
                                  </td>
                                  <td>
                                    <a style="text-decoration:none;" target="_blank" href=""><img width="181" height="49" style="display:block;border:0;" border="0" src="http://d4e7wxbvl20c1.cloudfront.net/images.flyer.fr/emailling/bonneaffaire.jpg"></a>
                                  </td> 
                                </tr>
                            </table>
                        </td> 
                      </tr>

                      <tr>
                        <td height="14">
                        </td> 
                      </tr>


                      <tr>
                        <td>';
    
        $bodyFooter ='</td> 
                      </tr>
                      <tr>
                        <td height="7"></td> 
                      </tr>
                        <td height="10">

                        </td> 
                      </tr>
                      <tr>
                        <td>
                            <img width="620" height="134" style="display:block;border:0;" border="0" src="http://d4e7wxbvl20c1.cloudfront.net/images.flyer.fr/emailling/block.jpg" />
                        </td> 
                      </tr>

                  </table>
                  </body>
                </html>';

        $my_module = 'pccontact';
        $my_mail_token = microtime();
        
        $system = drupal_mail_system($my_module, $my_mail_token);
        
        $from = variable_get('system_mail', 'support@flyer.fr');
       
    // info mail admin
        $to = variable_get('system_mail', 'nabil.b@oneoweb.com');
        $message = array(
            'id' => $my_module . '_' . $my_mail_token,
            'to' => $to,
            'subject' => 'Demande de rappel - Mail de confirmation',
            'body' => array($bodyAdmin),
            'headers' => array(
                'From' => $from,
                'Sender' => $from,
                'Return-Path' => $from,
                'MIME-Version' => '1.0',
                'Content-Type' => 'text/html; charset=UTF-8; format=flowed',
                'Content-Transfer-Encoding' => '8Bit',
                'X-Mailer' => 'Drupal',
            ),
        );
       
        $message = $system->format($message);
        $resAdmin = $system->mail($message);   
            
    // info mail client
        $to = variable_get('system_mail', $_GET['email']);
        $message = array(
                    'id' => $my_module . '_' . $my_mail_token,
                    'to' => $to,
                    'subject' => 'Demande de rappel - Mail de confirmation',
                    'body' => array($bodyHeader.$bodyClt.$bodyFooter),
                    'headers' => array(
                        'From' => $from,
                        'Sender' => $from,
                        'Return-Path' => $from,
                        'MIME-Version' => '1.0',
                        'Content-Type' => 'text/html; charset=UTF-8; format=flowed',
                        'Content-Transfer-Encoding' => '8Bit',
                        'X-Mailer' => 'Drupal',
                    ),
            );
          
            $message = $system->format($message);
            $resClt = $system->mail($message);

            if ($resClt && $resAdmin) {
                $data = true;
            } else {
               $data = false;
            }

        }else{
          
          $data = false;
          
        }

    drupal_json_output(array( 'data' => $data));
}

// fonction de test mail 
//function sendmail(){
// 
//   $message2  = '<div id="messageSent" style="display: block;text-align: center;">
//                    <h3>VOTRE DEMANDE A BIEN ÉTÉ PRISE EN COMPTE !</h3>
//                    <p>Un conseiller vous répondra dans les plus brefs délais.
//                    Nous vous remercions de votre confiance.</p><p class="orange">
//                    Vous avez reçu un email de confirmation</p>
//                    </div>';
//  
//
//           $my_module = 'pccontact';
//           $my_mail_token = microtime();
//      
//            $from = variable_get('system_mail', 'support@flyer.fr');
//            $to = variable_get('system_mail', 'n_bentounsi@yahoo.com');
// 
//        $message = array(
//            'id' => $my_module . '_' . $my_mail_token,
//            'to' => $to,
//            'subject' => 'mail flyer',
//            'body' => array($message2),
//            'headers' => array(
//                'From' => $from,
//                'Sender' => $from,
//                'Return-Path' => $from,
//                'MIME-Version' => '1.0',
//                'Content-Type' => 'text/html; charset=UTF-8; format=flowed',
//                'Content-Transfer-Encoding' => '8Bit',
//                'X-Mailer' => 'Drupal',
//            ),
//        );
//        $system = drupal_mail_system($my_module, $my_mail_token);
//        $message = $system->format($message);
//        if ($system->mail($message)) {
//            print   t('Vos coordonnées ont bien été envoyées');
//        } else {
//           print  'Erreur d\'envoie !';
//        }
//     
//  
//} 

