<?php

function pcformpopup_menu() {
 $items = array();
 
  $items['pcformpopup/page'] = array(
    'page callback' => 'pcformpopup_page',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );
 
  $items['pcformpopup/%ctools_js'] = array(
    'page callback' => 'pcformpopup_callback',
    'page arguments' => array(1),
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );
 
  return $items;
}

function pcformpopup_block_info() {
   $blocks = array();
   $blocks['list'] = array(
     'info' => t('Contact form popup'),
     'cache' => DRUPAL_NO_CACHE,
   );
   return $blocks;
}

function pcformpopup_block_view($delta = ''){
    $block = array();	
    switch ($delta){      
        case 'list':
          $items = pcformpopup_page();
           
            $block['subject'] = t('Contact');
            $block['content'] = array(
                    '#theme' => 'pcformpopup',        
                    '#items'=> $items,
                    '#title'=> t('Contact popup'),
                );
        break;
            
    }
 return $block;
}

function pcformpopup_theme($existing, $type, $theme, $path){
    return array(
	'pcformpopup' => array(
	'template' => 'pcformpopup',
	'variables'=> array('items' => NULL,'title'=>NULL)),
	);
}

/**
 * Helper function to make a link.
 */
function _pcformpopup_make_link($link_text = '') {
  // Set a default value if no text in supplied.
  if (empty($link_text)) {
    $link_text = 'Je souhaite être rappelé(e)';
  }
 
  return '<div id="magical-modal-link">' . l($link_text, 'pcformpopup/nojs', array('attributes' => array('class' => 'ctools-use-modal'))) . '</div>';
}



/**
 * An example page.
 */
function pcformpopup_page() {
  // Load the modal library and add the modal javascript.
  ctools_include('modal');
  ctools_modal_add_js();
 // Create our own javascript that will be used to theme a modal.
    $sample_style = array(
    'ctools-sample-style' => array(
    'modalSize' => array(
    'type' => 'fixed',
    'width' => 500,
    'height' => 400,
    'addWidth' => 20,
    'addHeight' => 15,
    ),
    'modalOptions' => array(
    'opacity' => .5,
    'background-color' => '#000',
    ),
    'animation' => 'fadeIn',
    'modalTheme' => 'CToolsSampleModal',
    ),
    );
    drupal_add_js($sample_style, 'setting'); 
  return _pcformpopup_make_link('Je souhaite être rappelé(e)');
}

/**
 * Ajax menu callback.
 */
function pcformpopup_callback($ajax) {
  if ($ajax) {
    ctools_include('ajax');
    ctools_include('modal');
 
    $form_state = array(
      'ajax' => TRUE,
      'title' => t(''),
    );
 
    // Use ctools to generate ajax instructions for the browser to create
    // a form in a modal popup.
    $output = ctools_modal_form_wrapper('pcformpopup_form', $form_state);
 
    // If the form has been submitted, there may be additional instructions
    // such as dismissing the modal popup.
    if (!empty($form_state['ajax_commands'])) {
      $output = $form_state['ajax_commands'];
        // pcformpopup_mail('default_from', 'nabil.b@oneoweb.com', 'Je souhaite être rappelé', $output);
    }
 
    // Return the ajax instructions to the browser via ajax_render().
    print ajax_render($output);    
    drupal_exit();
  }else {
    return drupal_get_form('pcformpopup_form');
  }
}



/**
 * Drupal form to be put in a modal.
 */
function pcformpopup_form($form, $form_state) {
  $form = array();
 
  $form['titrepopup'] = array(
    '#markup' =>'<span class="titrepopup">Je souhaite être rappelé(e)</span>',
  );
  $form['presentation'] = array(
    '#markup' => '<span class="pre-popup">Merci de remplir le formulairesuivant afin qu\'un operateur <br />FLYER puisse prendre contact avec vous par téléphone.<span>',
  );

  $form['nom'] = array(
    '#type' => 'textfield',
    '#title' => t('Nom'),
    '#required' => TRUE,
  );
   $form['prenom'] = array(
    '#type' => 'textfield',
    '#title' => t('Prénom'),
    '#required' => TRUE,

  ); 
    $form['telephone'] = array(
    '#type' => 'textfield',
    '#title' => t('Téléphone'),
    '#required' => TRUE,

  );

$form['email'] = array(
    '#type' => 'textfield',
    '#title' => t('Adresse email'),
    '#required' => TRUE,
  );
$form['notice'] = array(
    '#markup' => t('Les champs avec un astérisque (<span>*</span>)sont à remplir obligatoirement.'),
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Envoyer'),
    '#attributes' => array(
          'class' => array('flesh'),
    ),
  );
 
  return $form;
}



/**
 * Drupal form submit handler.
 */
function pcformpopup_form_submit(&$form, &$form_state) {
 
   $form_state['ajax_commands'][] = ctools_modal_command_dismiss();

   $message  = 'Nom : '.$form_state['values']['nom'].'<br />';
   $message .= 'Prénom : '.$form_state['values']['prenom'].'<br />';
   $message .= 'Tél : '.$form_state['values']['telephone'].'<br />';
   $message .= 'Email : '.$form_state['values']['email'].'<br />';

  // pcformpopup_mail('default_from', 'nabil.b@oneoweb.com', 'Je souhaite être rappelé', $message);
   
 // $form_state['ajax_commands'][] = ajax_command_replace('#magical-modal-link', "good");
   // Tell the browser to close the modal

  // Tell the browser to replace the old link with the new one.


}
function pcformpopup_form_validate(&$form, &$form_state) {
    
    if (!valid_email_address($form_state['values']['email'])) {
      form_set_error('mail', t('You must enter a valid e-mail address.'));
    }
    
}

/**
 * mail function 
 */

function pcformpopup_mail($from = 'default_from', $to, $subject, $message) {
        $my_module = 'pcformpopup';
        $my_mail_token = microtime();
        if ($from == 'default_from') {
            // Change this to your own default 'from' email address.
            $from = variable_get('system_mail', 'support@flyer.fr');
        }
 
        $message = array(
            'id' => $my_module . '_' . $my_mail_token,
            'to' => $to,
            'subject' => $subject,
            'body' => array($message),
            'headers' => array(
                'From' => $from,
                'Sender' => $from,
                'Return-Path' => $from,
                'MIME-Version' => '1.0',
                'Content-Type' => 'text/html; charset=UTF-8; format=flowed',
                'Content-Transfer-Encoding' => '8Bit',
                'X-Mailer' => 'Drupal',
            ),
        );
        $system = drupal_mail_system($my_module, $my_mail_token);
        $message = $system->format($message);
        if ($system->mail($message)) {
            return   t('Vos coordonnées ont bien été envoyées');
        } else {
           return  'Erreur d\'envoie !';
        }
}