<?php
// $Id: keyword_ruels.install,v 1.1 2009/05/25 09:46:56 miruoss Exp $

/**
 * @file
 * Installer of the keyword based rules module for the SEO Checker.
 *
 */

/**
 * Implementation of hook_install().
 */
function keyword_rules_install() {
  $weight = db_result(db_query('SELECT weight FROM {system} WHERE name = "seo_checker"'));
  db_query("UPDATE {system} SET weight = %d WHERE name = 'keyword_rules'", ($weight+1));
}

?>